### ISSUE TITLE
Не отображаются галочки

### ISSUE THREAD

**Issue by Gadel9152** [openvk/mobvk#18]
Их нет нигде

**Comment by rencornationers** [comment]
Да их и в полной версии нема...

**Comment by Gadel9152** [comment]
> Да их и в полной версии нема...

![Screenshot_2022-02-09-13-34-34-845_com vivaldi browser](https://user-images.githubusercontent.com/38789158/153180686-0d8ba40c-008c-4049-b404-5a759e788025.jpg)
